// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    NEXT_PUBLIC_SUPABASE_URL:string,
    SUPABASE_SERVICE_ROLE_KEY:string,
}
