// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    NEXT_PUBLIC_REOWN_PROJECT_ID:string,
    NEXT_PUBLIC_XAMAN_API_KEY:string,
    NEXT_PUBLIC_SUPABASE_URL:string,
    NEXT_PUBLIC_SUPABASE_ANON_KEY:string,
    SUPABASE_SERVICE_ROLE_KEY:string,
}
